version: "3.5"
services:
  pacman_package:
    build:
      context: .
    command: sh build.sh
    volumes:
      - .:/home/builder/kmeldb-ui-packaging
    working_dir: /home/builder/kmeldb-ui-packaging
