version: "3.5"
services:
  pacman_package:
    build:
      context: ..
      dockerfile: archlinux/Dockerfile
    command: sh build.sh
    volumes:
      - ./out:/home/builder/kmeldb-ui-packaging/archlinux/out
    working_dir: /home/builder/kmeldb-ui-packaging/archlinux
