version: "3.5"
services:
  source_package:
    build:
      context: ../..
      dockerfile: ubuntu/disco/Dockerfile
    command: sh publish-ppa.sh -d disco -n
    volumes:
      - ../out:/home/builder/kmeldb-ui/ubuntu/out
    working_dir: /home/builder/kmeldb-ui/ubuntu
